// envelope.mjs — PWA install envelope per pwa-gallery spec 04 (prototype, feeds ticket 07).
// Wraps a pipeline-built self-contained artifact HTML with:
//   manifest.json          (name/short_name, standalone, ./ scope, accent theme_color)
//   sw.js                  precache-only, revisioned cache name, prune-on-activate
//   <head> links           manifest, theme-color, apple-touch-icon, iOS metas
//   sw registration        inline script before </body>
// Cache-busting: revision = sha256(index.html)[0..10]; precache URLs carry ?v=<rev>.
// Usage: node envelope.mjs --dir <dir> --name <slug> --accent <hex> [--title <Title>] [--short <Short>]
// The artifact HTML is expected at <dir>/<name>.html (build-artifact output).
// Produces <dir>/index.html (patched) + manifest.json + sw.js; icons must already
// exist in <dir> (icon-192/512/maskable/apple-touch) — generated via generate-icons.mjs.

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const dir = resolve(arg("dir", "."));
const slug = arg("name", "artifact");
const accent = arg("accent", "#3FD8C4");
const title = arg("title", slug.replace(/-/g, " "));
const shortName = (arg("short", "") || title).slice(0, 12);

const srcPath = join(dir, `${slug}.html`);
const html = readFileSync(srcPath, "utf8");

if (html.includes('rel="manifest"')) {
  console.error(`[envelope] ${srcPath} already enveloped — aborting`);
  process.exit(1);
}

// ---- patch HTML: head links + sw registration ----
const headLinks = `<link rel="manifest" href="./manifest.json" />
<meta name="theme-color" content="${accent}" />
<link rel="icon" type="image/png" sizes="192x192" href="./icon-192.png" />
<link rel="icon" href="data:," />
<link rel="apple-touch-icon" href="./apple-touch-icon.png" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta name="apple-mobile-web-app-title" content="${shortName}" />`;

const register = `<script>if('serviceWorker' in navigator){addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js')})}</script>\n</body>`;

if (!html.includes("</title>")) {
  console.error("[envelope] no </title> found — aborting");
  process.exit(1);
}
const patched = html.replace("</title>", `</title>\n${headLinks}`).replace("</body>", register);

// ---- revision: hash of the FINAL patched page (so envelope-only changes bump the rev) ----
const rev = createHash("sha256").update(patched).digest("hex").slice(0, 10);

// ---- manifest.json ----
const manifest = {
  name: title,
  short_name: shortName,
  start_url: "./",
  scope: "./",
  id: "./",
  display: "standalone",
  theme_color: accent,
  background_color: accent,
  icons: [
    { src: "./icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
    { src: "./icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
    { src: "./icon-512-maskable.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
  ],
};
writeFileSync(join(dir, "manifest.json"), JSON.stringify(manifest, null, 2), "utf8");

// ---- sw.js ----
// Navigation = network-first (fresh when online, rev'd-copy fallback offline).
// Versioned assets = cache-first (immutable while this SW rev is alive).
// "./" is deliberately NOT precached: the directory URL is the navigation URL
// and must never be pinned to a stale copy.
const assets = [
  `./index.html?v=${rev}`,
  "./manifest.json",
  "./icon-192.png",
  "./icon-512.png",
  "./icon-512-maskable.png",
  "./apple-touch-icon.png",
];
const sw = `// ${slug} service worker — generated by envelope.mjs (rev ${rev})
const CACHE = '${slug}-${rev}';
const PRECACHE = ${JSON.stringify(assets)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('${slug}-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (e.request.mode === 'navigate') {
    // network-first: stale-free online, rev'd copy offline
    e.respondWith(
      fetch(e.request)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put('./index.html?v=${rev}', copy));
          return res;
        })
        .catch(() => caches.match('./index.html?v=${rev}'))
    );
    return;
  }
  e.respondWith(
    caches.match(e.request).then((hit) => hit || fetch(e.request))
  );
});
`;
writeFileSync(join(dir, "sw.js"), sw, "utf8");

// ---- write patched page AFTER rev computed ----
writeFileSync(join(dir, "index.html"), patched, "utf8");

console.log(`[envelope] ${slug}: rev=${rev}`);
console.log(`[envelope] manifest.json + sw.js + index.html -> ${dir}`);
console.log(`[envelope] precache: ${assets.join(", ")}`);